# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get the output
        run: |
          echo "${{ steps.deploy.outputs.notify }}"

      - name: Install hexo if not exist
        run: |
          if ! command -v hexo &> /dev/null
          then
              npm install -g hexo-cli 
              exit
          fi

      - name: Setting git authen
        run: |
          /usr/bin/git remote rm origin
          /usr/bin/git remote add origin ***github.com/${{ github.repository }}.git
          /usr/bin/git add --all
          /usr/bin/git config user.name ${{ github.actor }}
          /usr/bin/git config user.email ${{ github.actor }}@users.noreply.github.com

      - name: Deploy
        run: hexo clean && hexo deploy
          
      # - name: Deploy
      #   # You may pin to the exact commit or the version.
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.DEPLOY_KEY }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     publish_branch: gh-pages
      #     disable_nojekyll: true
      #     force_orphan: true

      - name: Get the output
        run: |
          echo "${{ steps.deploy.outputs.notify }}"
